# Generated by Django 5.1.4 on 2025-01-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pouya', '0002_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
