# Generated by Django 5.1.4 on 2025-01-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='coursecategory',
            table='course_categories',
        ),
        migrations.AlterModelTable(
            name='gradecategory',
            table='grade_categories',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
    ]
