# Generated by Django 5.1.4 on 2025-01-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
