# Generated by Django 5.1.4 on 2025-01-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_teacher_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_id',
            field=models.PositiveIntegerField(default=-1, unique=True),
        ),
    ]
