# Generated by Django 5.1.4 on 2025-01-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.PositiveIntegerField(default=-1, unique=True),
        ),
    ]
